# Based on wp-library _secret.yaml template

{{- if and .Values.repoSecrets .Values.repoSecrets.data (not (empty .Values.repoSecrets.data)) }}

{{- $argocdNamespace := coalesce .Values.repoSecrets.namespace "argocd" -}}
{{- $sshPrivateKey := .Values.repoSecrets.sshPrivateKey -}}

{{- range .Values.repoSecrets.repos }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .name $ }}-repo-secret
  {{- if not (empty $argocdNamespace) }}
  namespace: {{ $argocdNamespace }}
  {{- end }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque

stringData:
  type: {{ tpl .type $ | quote }}
  url: {{ tpl .url $ | quote }}
  sshPrivateKey: {{ $sshPrivateKey | quote }}
{{- end }}

{{- end }}
